const data = [

    {
        id: 0,
        item_name: 'Helsinki Lamp',
        description: 'Sleek and modern lamp with advanced LED technology and adjustable brightness settings. Illuminate with elegance.',
        image: 'https://www.ikea.com/es/es/images/products/blasverk-lampara-mesa-beige__1150245_pe884435_s5.jpg?f=l',
        price: 399,
        size: 'm',
        tag: 'From the Autumn Collection',
        total_quantity: 205,
        quantity: 0,
        review: '4',
        
    },
    {
        id: 1,
        item_name: 'The Compact Table',
        description: 'Crafted with high-quality materials and a timeless design, this table adds sophistication to any dining room.',
        image: 'https://www.ikea.com/es/es/images/products/tarsele-mesa-extensible-chapa-roble-negro__0916857_pe785431_s5.jpg?f=l',
        price: 2099,
        size: 'l',
        tag: '',
        total_quantity: 192,
        quantity: 0,
        review: '4',
        
    },
    {
        id: 2,
        item_name: 'Clear Chair',
        description: 'Its transparent design adds a touch of sophistication while blending seamlessly with any decor.',
        image: 'https://www.ikea.com/es/es/images/products/tobias-silla-transparente-cromado__0727342_pe735614_s5.jpg?f=l',
        price: 520,
        size: 'm',
        tag: 'New entry',
        total_quantity: 5,
        quantity: 399,
        review: '3',
        
    },
    {
        id: 3,
        item_name: 'Confetti Rug',
        description: 'With a soft texture and modern design, this rug is perfect for any home.',
        image: 'https://www.ikea.com/es/es/images/products/svardborg-alfombra-mano-hueso-multicolor__0989200_pe818408_s5.jpg?f=l',
        price: 3990,
        size: 'l',
        tag: '',
        total_quantity: 5,
        quantity: 97,
        review: '4',
        
    },
    {
        id: 4,
        item_name: 'The Original Green Couch',
        description: 'Perfect for lounging and entertaining, it adds a pop of color to any living space.',
        image: 'https://www.ikea.com/es/es/images/products/jattebo-sofa-modular-esquina-6-samsala-verde-amarillo-oscuro__1109619_pe870109_s5.jpg?f=l',
        price: 5399,
        size: 'l',
        tag: '',
        total_quantity: 5,
        quantity: 26,
        review: '5',
        
    },
    {
        id: 5,
        item_name: 'Simple Mug',
        description: 'Its minimalist design and high-quality material make it a timeless addition to any kitchen.',
        image: 'https://www.ikea.com/es/es/images/products/ofantligt-tazon-blanco__0711053_pe727928_s5.jpg?f=l',
        price: 9.99,
        size: 's',
        tag: '',
        total_quantity: 5,
        quantity: 243,
        review: '3',
        
    },
    {
        id: 6,
        item_name: 'Nordiska Bambu',
        description: 'With its natural look and durability, it brings a touch of nature to your home.',
        image: 'https://www.ikea.com/es/es/images/products/nordkisa-armario-abierto-puerta-corredera-bambu__0756084_pe748766_s5.jpg?f=xl',
        price: 2099,
        size: 'l',
        tag: 'From the Spring Collection',
        total_quantity: 164,
        quantity: 0,
        review: '4',
        
    },
    {
        id: 7,
        item_name: 'Rattan Chair',
        description: 'Its lightweight and durable design make it perfect for indoor or outdoor use, while its natural texture adds warmth to any decor.',
        image: 'https://www.ikea.com/es/es/images/products/ulriksberg-sillon-ratan-antracita__0672896_pe716932_s5.jpg?f=xl',
        price: 789,
        size: 'm',
        tag: '',
        total_quantity: 329,
        quantity: 0,
        review: '5',

    },
    {
        id: 8,
        item_name: 'POÄNG Armchair',
        description: 'Has stylish curved lines in bentwood, providing nice support for the neck and comfy resilience.',
        image: 'https://www.ikea.com/us/en/images/products/poaeng-armchair-brown-gunnared-light-green__1192116_pe900864_s5.jpg?f=l',
        price: 219,
        size: 'm',
        tag: '',
        total_quantity: 129,
        quantity: 0,
        review: '3',

    },
    {
        id: 9,
        item_name: 'White stained oak',
        description: 'This easy chair makes us believe in love at first sight, with its clean Scandinavian lines and airy expression.',
        image: 'https://www.ikea.com/us/en/images/products/froeset-chair-white-stained-oak-veneer__0824154_pe776005_s5.jpg?f=l',
        price: 395,
        size: 'm',
        tag: 'Hot this week',
        total_quantity: 79,
        quantity: 0,
        review: '5',
        
    },
    {
        id: 10,
        item_name: 'Pendant lamp 2014 ',
        description: 'A pull of the strings on IKEA PS 2014 pendant lamp gives the faintly glowing globe a shape that looks like a spaceship where light flows out of it.',
        image: 'https://www.ikea.com/us/en/images/products/ikea-ps-2014-pendant-lamp-black__1120764_pe873940_s5.jpg?f=l',
        price: 1245,
        size: 'm',
        tag: 'From the Futura Collection',
        total_quantity: 139,
        quantity: 0,
        review: '4', 

    },
    {
        id: 11,
        item_name: 'Nesting tables',
        description: 'This handy set of 2 matching nesting tables and 2 stools/side tables makes clever use of smaller spaces.',
        image: 'https://www.ikea.com/us/en/images/products/fridnaes-nesting-tables-with-stools-set-of-4-black-birch-effect__1038547_pe839730_s5.jpg?f=l',
        price: 219,
        size: 'm',
        tag: '',
        total_quantity: 200,
        quantity: 0,
        review: '4',

    },
    {
        id: 12,
        item_name: 'BESTÅ Storage ',
        description: 'Go ahead and put things aside for a while! A sideboard combination gives you plenty of space to store things and a surface to create an attractive display - or to unload serving dishes while you eat.',
        image: 'https://www.ikea.com/us/en/images/products/besta-storage-combination-w-doors-drawers-walnut-effect-light-gray-lappviken-walnut-effect-light-gray__0780706_pe760204_s5.jpg?f=l',
        price: 529,
        size: 'l',
        tag: '',
        total_quantity: 627,
        quantity: 0,
        review: '5',
        
    },

]

export default data;